# Generated by Django 6.0.6 on 2026-06-21 06:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookmarkFolder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The created DateTime of the object', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='The updated DateTime of the object', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The UUID of the object', primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the bookmark folder', max_length=100, verbose_name='name')),
                ('user', models.ForeignKey(help_text='The user who owns the bookmark folder', on_delete=django.db.models.deletion.CASCADE, related_name='bookmark_folders', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'bookmark folder',
                'verbose_name_plural': 'bookmark folders',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The created DateTime of the object', verbose_name='created at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The UUID of the object', primary_key=True, serialize=False, verbose_name='ID')),
                ('article_publication', models.ForeignKey(help_text='The article publication being bookmarked', on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='articles.articlepublication', verbose_name='article publication')),
                ('user', models.ForeignKey(help_text='The user who owns the bookmark', on_delete=django.db.models.deletion.CASCADE, related_name='article_bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('folder', models.ForeignKey(help_text='The folder that contains the bookmark', on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='bookmarks.bookmarkfolder', verbose_name='folder')),
            ],
            options={
                'verbose_name': 'bookmark',
                'verbose_name_plural': 'bookmarks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bookmarkfolder',
            index=models.Index(fields=['user', 'created_at'], name='bookmarks_b_user_id_224b13_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookmarkfolder',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_bookmark_folder_name_per_user'),
        ),
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['user', 'created_at'], name='bookmarks_b_user_id_f7315e_idx'),
        ),
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['folder', 'created_at'], name='bookmarks_b_folder__84d09a_idx'),
        ),
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['article_publication', 'created_at'], name='bookmarks_b_article_eb83fa_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookmark',
            constraint=models.UniqueConstraint(fields=('user', 'article_publication'), name='unique_bookmark_article_publication_per_user'),
        ),
    ]
