# Generated by Django 6.0.5 on 2026-05-11 05:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The created DateTime of the object', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='The updated DateTime of the object', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The UUID of the object', primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_object_id', models.UUIDField(help_text='The UUID of the actor object', verbose_name='actor object ID')),
                ('target_object_id', models.UUIDField(blank=True, help_text='The UUID of the target object', null=True, verbose_name='target object ID')),
                ('action_object_object_id', models.UUIDField(blank=True, help_text='The UUID of the action object', null=True, verbose_name='action object ID')),
                ('notification_type', models.CharField(choices=[('mention', 'Mention')], help_text='The type of notification', max_length=50, verbose_name='notification type')),
                ('verb', models.CharField(help_text='The action verb describing what happened', max_length=255, verbose_name='verb')),
                ('is_read', models.BooleanField(db_index=True, default=False, help_text='Whether the notification has been read', verbose_name='is read')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Additional data for the notification', verbose_name='data')),
                ('dedupe_key', models.CharField(db_index=True, help_text='Unique key to prevent duplicate notifications', max_length=255, unique=True, verbose_name='dedupe key')),
                ('action_object_content_type', models.ForeignKey(blank=True, help_text='The content type of the action object', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_action_object', to='contenttypes.contenttype', verbose_name='action object content type')),
                ('actor_content_type', models.ForeignKey(help_text='The content type of the actor', on_delete=django.db.models.deletion.CASCADE, related_name='notification_actor', to='contenttypes.contenttype', verbose_name='actor content type')),
                ('recipient', models.ForeignKey(help_text='The user who receives the notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='recipient')),
                ('target_content_type', models.ForeignKey(blank=True, help_text='The content type of the target', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_target', to='contenttypes.contenttype', verbose_name='target content type')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['recipient', 'notification_type'], name='notificatio_recipie_028906_idx'), models.Index(fields=['recipient', 'created_at'], name='notificatio_recipie_f39341_idx')],
            },
        ),
    ]
