# Generated by Codex on 2026-06-19

from django.db import migrations, models


def split_payload_and_recipients(apps, schema_editor):
    NotificationEvent = apps.get_model("notifications", "NotificationEvent")
    UserSubscription = apps.get_model("users", "UserSubscription")

    for event in NotificationEvent.objects.all().iterator():
        payload = dict(event.payload or {})
        recipients = payload.pop("recipient_ids", [])
        if event.reason == 4 and event.actor_id:
            recipients = list(
                UserSubscription.objects.filter(
                    subscribed_to_id=event.actor_id,
                ).values_list("subscriber_id", flat=True)
            )

        if event.reason == 1:
            channel = 1
        elif event.reason == 2:
            channel = 2
        elif event.reason == 4:
            channel = 4
        else:
            channel = 3

        event.payload = payload
        event.recipients = [str(recipient_id) for recipient_id in recipients]
        event.channel = channel
        event.save(update_fields=["payload", "recipients", "channel"])


def merge_recipients_into_payload(apps, schema_editor):
    NotificationEvent = apps.get_model("notifications", "NotificationEvent")

    for event in NotificationEvent.objects.all().iterator():
        payload = dict(event.payload or {})
        if event.recipients:
            payload["recipient_ids"] = event.recipients
        event.payload = payload
        event.save(update_fields=["payload"])


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
        ("users", "0002_usersubscription"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="notificationevent",
            name="notificatio_event_t_58f16e_idx",
        ),
        migrations.RenameField(
            model_name="notificationevent",
            old_name="event_type",
            new_name="reason",
        ),
        migrations.RenameField(
            model_name="notificationevent",
            old_name="data",
            new_name="payload",
        ),
        migrations.AddField(
            model_name="notificationevent",
            name="channel",
            field=models.IntegerField(
                choices=[
                    (1, "mentions"),
                    (2, "comments"),
                    (3, "system"),
                    (4, "subscriptions"),
                ],
                db_index=True,
                default=3,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="notificationevent",
            name="recipients",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(split_payload_and_recipients, merge_recipients_into_payload),
        migrations.AlterField(
            model_name="notificationevent",
            name="reason",
            field=models.IntegerField(
                choices=[
                    (1, "mention"),
                    (2, "reply"),
                    (3, "system"),
                    (4, "subscription"),
                ],
                db_index=True,
            ),
        ),
        migrations.AddIndex(
            model_name="notificationevent",
            index=models.Index(fields=["channel", "created_at"], name="notificatio_channel_7086bb_idx"),
        ),
        migrations.AddIndex(
            model_name="notificationevent",
            index=models.Index(fields=["reason", "created_at"], name="notificatio_reason_c4bfd9_idx"),
        ),
    ]
