# Generated by Django 6.0.3 on 2026-03-21 06:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntervalSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('every', models.PositiveIntegerField(help_text='Number of interval periods to wait before next execution', verbose_name='number of periods')),
                ('period', models.CharField(choices=[('seconds', 'seconds'), ('minutes', 'minutes'), ('days', 'days'), ('weeks', 'weeks')], help_text='The type of period used by the schedule', max_length=50, verbose_name='interval period')),
            ],
            options={
                'verbose_name': 'interval schedule',
                'verbose_name_plural': 'interval schedules',
            },
        ),
        migrations.CreateModel(
            name='PeriodicTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A short description for this task', max_length=150, verbose_name='name')),
                ('description', models.TextField(blank=True, default='', help_text='A extended description for this task', verbose_name='description')),
                ('task_path', models.CharField(help_text='The path of the task function to be run', max_length=255, verbose_name='task path')),
                ('queue_name', models.CharField(help_text='The name of the queue that this task belongs to', max_length=100, verbose_name='queue name')),
                ('args', models.JSONField(blank=True, default=list, help_text='The positional arguments passed to the function', verbose_name='positional arguments')),
                ('kwargs', models.JSONField(blank=True, default=dict, help_text='The keyword arguments passed to the function', verbose_name='keyword arguments')),
                ('is_enabled', models.BooleanField(db_index=True, default=True, help_text='Only enabled tasks will be queued', verbose_name='enabled')),
                ('started_at', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, help_text='The start time of the task', verbose_name='start at')),
                ('next_run_at', models.DateTimeField(blank=True, help_text='The next run time of the task', verbose_name='next run at')),
                ('last_run_at', models.DateTimeField(blank=True, help_text='The last run time of the task', null=True, verbose_name='last run at')),
                ('interval', models.ForeignKey(help_text='The time between two task executions', on_delete=django.db.models.deletion.PROTECT, to='tasks.intervalschedule', verbose_name='interval')),
            ],
            options={
                'verbose_name': 'periodic task',
                'verbose_name_plural': 'periodic tasks',
                'ordering': ['-next_run_at'],
            },
        ),
    ]
