# Generated by Django 6.0.3 on 2026-04-05 01:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntervalSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('every', models.PositiveIntegerField(help_text='Number of interval periods to wait before next execution', verbose_name='number of periods')),
                ('period', models.CharField(choices=[('millisecond', 'millisecond'), ('second', 'second'), ('minute', 'minute'), ('hour', 'hour'), ('day', 'day'), ('week', 'week')], help_text='The type of period used by the schedule', max_length=50, verbose_name='interval period')),
            ],
            options={
                'verbose_name': 'interval schedule',
                'verbose_name_plural': 'interval schedules',
                'constraints': [models.UniqueConstraint(fields=('every', 'period'), name='unique_interval_schedule')],
            },
        ),
        migrations.CreateModel(
            name='PeriodicTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A short, unique description for this task', max_length=150, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, default='', help_text='A extended description for this task', verbose_name='description')),
                ('task', models.CharField(help_text='The path of the task function to be run', max_length=255, verbose_name='task path')),
                ('queue_name', models.CharField(help_text='The name of the queue that this task belongs to', max_length=100, verbose_name='queue name')),
                ('args', models.JSONField(blank=True, default=list, help_text='The positional arguments passed to the function', verbose_name='positional arguments')),
                ('kwargs', models.JSONField(blank=True, default=dict, help_text='The keyword arguments passed to the function', verbose_name='keyword arguments')),
                ('is_enabled', models.BooleanField(db_index=True, default=True, help_text='Only enabled tasks will be queued', verbose_name='enabled')),
                ('last_enqueued_at', models.DateTimeField(blank=True, editable=False, help_text='The last enqueued DateTime of the task', null=True, verbose_name='last enqueued at')),
                ('next_enqueue_at', models.DateTimeField(blank=True, help_text='The next enqueue DateTime of the task', verbose_name='next enqueue at')),
                ('last_started_at', models.DateTimeField(blank=True, editable=False, help_text='The last started DateTime of the task', null=True, verbose_name='last started at')),
                ('last_finished_at', models.DateTimeField(blank=True, editable=False, help_text='The last finished DateTime of the task', null=True, verbose_name='last finished at')),
                ('interval', models.ForeignKey(help_text='The time between two task executions', on_delete=django.db.models.deletion.PROTECT, related_name='periodic_tasks', to='tasks.intervalschedule', verbose_name='interval')),
            ],
            options={
                'verbose_name': 'periodic task',
                'verbose_name_plural': 'periodic tasks',
                'ordering': ['-next_enqueue_at'],
            },
        ),
    ]
