services:
  postgres:
    volumes:
      - postgres_data_pro:/var/lib/postgresql
    env_file:
    - ./env/.env.pro
  
  redis:
    command: >
      sh -c 'redis-server --appendonly yes --requirepass "$$REDIS_PASSWORD"'
    env_file:
    - ./env/.env.pro

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    command: >
      sh -c "
        python manage.py collectstatic --noinput &&
        python manage.py init_tasks &&
        daphne -b 0.0.0.0 -p 8000 backend.asgi:application
      "
    environment:
      - DJANGO_ENV: pro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend-production.rule=Host(`api.aliencommons.lazyalienserver.top`)"
      - "traefik.http.routers.backend-production.entrypoints=websecure"
      - "traefik.http.routers.backend-production.tls.certresolver=le"
      - "traefik.http.services.backend-production.loadbalancer.server.port=8000"
    volumes:
      - /srv/alien-commons/pro/media:/code/media
      - /srv/alien-commons/pro/static:/code/staticfiles

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      VITE_MODE: production
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend-production.rule=Host(`aliencommons.lazyalienserver.top`)"
      - "traefik.http.routers.frontend-production.entrypoints=websecure"
      - "traefik.http.routers.frontend-production.tls.certresolver=le"
      - "traefik.http.services.frontend-production.loadbalancer.server.port=80"

  media:
    image: nginx:alpine
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.media.rule=Host(`api.aliencommons.lazyalienserver.top`) && PathPrefix(`/media`)"
      - "traefik.http.routers.media.entrypoints=websecure"
      - "traefik.http.routers.media.tls.certresolver=le"
      - "traefik.http.services.media.loadbalancer.server.port=80"
    restart: unless-stopped
    volumes:
      - /srv/alien-commons/pro/media:/usr/share/nginx/html/media:ro
  
  static:
    image: nginx:alpine
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.static.rule=Host(`api.aliencommons.lazyalienserver.top`) && PathPrefix(`/static`)"
      - "traefik.http.routers.static.entrypoints=websecure"
      - "traefik.http.routers.static.tls.certresolver=le"
      - "traefik.http.services.static.loadbalancer.server.port=80"
    restart: unless-stopped
    volumes:
      - /srv/alien-commons/pro/static:/usr/share/nginx/html/static:ro

volumes:
  postgres_data_pro:
  