apiVersion: 1
prune: true

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    editable: false
    version: 1
    jsonData:
      maxLines: 1000
