# Generated by Django 6.0.6 on 2026-06-21 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='target',
            field=models.ForeignKey(help_text='The content target this comment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.contenttarget', verbose_name='target'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['target', 'created_at'], name='comments_co_target__3011cc_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent', 'created_at'], name='comments_co_parent__10bc81_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author', 'created_at'], name='comments_co_author__a235af_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['is_deleted', 'created_at'], name='comments_co_is_dele_95809f_idx'),
        ),
    ]
