# Generated by Django 6.0.5 on 2026-05-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='mentions',
            field=models.JSONField(blank=True, default=list, help_text='Ordered user IDs referenced by mention tokens in the comment body', verbose_name='mentions'),
        ),
    ]
