# Generated by Django 6.0.3 on 2026-03-23 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodictask',
            old_name='task_path',
            new_name='task',
        ),
        migrations.RemoveField(
            model_name='periodictask',
            name='started_at',
        ),
        migrations.AlterField(
            model_name='intervalschedule',
            name='period',
            field=models.CharField(choices=[('millisecond', 'millisecond'), ('second', 'second'), ('minute', 'minute'), ('hour', 'hour'), ('day', 'day'), ('week', 'week')], help_text='The type of period used by the schedule', max_length=50, verbose_name='interval period'),
        ),
        migrations.AlterField(
            model_name='periodictask',
            name='interval',
            field=models.ForeignKey(help_text='The time between two task executions', on_delete=django.db.models.deletion.PROTECT, related_name='periodic_tasks', to='tasks.intervalschedule', verbose_name='interval'),
        ),
        migrations.AlterField(
            model_name='periodictask',
            name='name',
            field=models.CharField(help_text='A short, unique description for this task', max_length=150, unique=True, verbose_name='name'),
        ),
        migrations.AddConstraint(
            model_name='intervalschedule',
            constraint=models.UniqueConstraint(fields=('every', 'period'), name='unique_interval_schedule'),
        ),
    ]
