# Generated by Django 6.0.3 on 2026-03-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_task_path_periodictask_task_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodictask',
            options={'ordering': ['-next_enqueue_at'], 'verbose_name': 'periodic task', 'verbose_name_plural': 'periodic tasks'},
        ),
        migrations.RemoveField(
            model_name='periodictask',
            name='last_run_at',
        ),
        migrations.RemoveField(
            model_name='periodictask',
            name='next_run_at',
        ),
        migrations.AddField(
            model_name='periodictask',
            name='last_enqueued_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='The last enqueued DateTime of the task', null=True, verbose_name='last enqueued at'),
        ),
        migrations.AddField(
            model_name='periodictask',
            name='last_finished_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='The last finished DateTime of the task', null=True, verbose_name='last finished at'),
        ),
        migrations.AddField(
            model_name='periodictask',
            name='last_started_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='The last started DateTime of the task', null=True, verbose_name='last started at'),
        ),
        migrations.AddField(
            model_name='periodictask',
            name='next_enqueue_at',
            field=models.DateTimeField(blank=True, default=1, help_text='The next enqueue DateTime of the task', verbose_name='next enqueue at'),
            preserve_default=False,
        ),
    ]
