FILE_TYPE_MAP = {
    # ----- Image -----
    "image/jpeg": "JPEG",
    "image/pjpeg": "JPEG (Progressive)",
    "image/png": "PNG",
    "image/apng": "APNG",
    "image/gif": "GIF",
    "image/webp": "WEBP",
    "image/bmp": "BMP",
    "image/x-windows-bmp": "BMP (Windows)",
    "image/tiff": "TIFF",
    "image/x-tiff": "TIFF (Extended)",
    "image/heic": "HEIC (iOS)",
    "image/heif": "HEIF",
    "image/avif": "AVIF",
    "image/x-icon": "ICO",
    "image/vnd.microsoft.icon": "ICO",
    "image/svg+xml": "SVG",
    "image/x-pict": "PICT",
    # ----- Video -----
    "video/mp4": "MP4",
    "video/webm": "WebM",
    "video/ogg": "Ogg Video",
    "video/x-msvideo": "AVI",
    "video/x-ms-wmv": "WMV",
    "video/quicktime": "MOV",
    "video/x-flv": "FLV",
    "video/mpeg": "MPEG",
    "video/3gpp": "3GP",
    "video/3gpp2": "3G2",
    "video/x-matroska": "MKV",
    # ----- Audio -----
    "audio/mpeg": "MP3",
    "audio/mp3": "MP3 (Alias)",
    "audio/aac": "AAC",
    "audio/ogg": "Ogg Audio",
    "audio/wav": "WAV",
    "audio/x-wav": "WAV (Extended)",
    "audio/webm": "WebM Audio",
    "audio/flac": "FLAC",
    "audio/x-flac": "FLAC (Extended)",
    "audio/3gpp": "3GP Audio",
    "audio/amr": "AMR",
    "audio/x-ms-wma": "WMA",
    "audio/mp4": "M4A",
}
