# Generated by Django 6.0.5 on 2026-05-11 03:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The created DateTime of the object', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='The updated DateTime of the object', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The UUID of the object', primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether the object is deleted', verbose_name='deleted')),
                ('body', models.TextField(help_text='The post body', verbose_name='body')),
                ('author', models.ForeignKey(help_text='The author of the post', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_posts', to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name': 'community post',
                'verbose_name_plural': 'community posts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['author', 'created_at'], name='posts_commu_author__2f7e8e_idx'), models.Index(fields=['is_deleted', 'created_at'], name='posts_commu_is_dele_0ee537_idx')],
            },
        ),
    ]
