# Generated by Django 6.0.5 on 2026-05-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='mentions',
            field=models.JSONField(blank=True, default=list, help_text='Ordered user IDs referenced by mention tokens in the post body', verbose_name='mentions'),
        ),
    ]
