site_name: AlienMark Docs

nav:
  - Home: index.md
  - Syntax: syntax.md

theme:
  name: material
  language: en

plugins:
  - search
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          name: English
          default: true
          build: true
        - locale: zh
          name: 中文
          build: true
          nav_translations:
            Home: 首页
            Syntax: 语法
