[project]
site_name = "AlienMark 文档"
docs_dir = "docs/zh"
site_dir = "site/zh"
nav = [{ "首页" = "index.md" }, { "语法" = "syntax.md" }]

[project.theme]
language = "zh"

[project.extra]
alternate = [
  { name = "English", link = "/", lang = "en" },
  { name = "中文", link = "/zh/", lang = "zh" },
]
