[project]
site_name = "AlienMark Docs"
docs_dir = "docs/en"
site_dir = "site"
nav = [{ Home = "index.md" }, { Syntax = "syntax.md" }]

[project.theme]
language = "en"

[project.extra]
alternate = [
  { name = "English", link = "/", lang = "en" },
  { name = "中文", link = "/zh/", lang = "zh" },
]
