name: alien-commons-pro

services:
  postgres:
    env_file:
      - ../env/.env.pro
    volumes:
      - postgres_data_pro:/var/lib/postgresql
  
  redis:
    command: >
      sh -c 'redis-server --appendonly yes --requirepass "$$REDIS_PASSWORD"'
    env_file:
      - ../env/.env.pro
  
  backend-init:
    build:
      context: ../../apps/backend
      dockerfile: Dockerfile
    working_dir: /code
    command: >
      sh -c "python manage.py migrate && python manage.py init_tasks"
    environment:
      DJANGO_ENV: pro
    depends_on:
      - postgres
      - redis

  backend-api:
    build:
      context: ../../apps/backend
      dockerfile: Dockerfile
    working_dir: /code
    restart: unless-stopped
    command: >
      sh -c "gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
    environment:
      - DJANGO_ENV: pro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend-production.rule=Host(`api.aliencommons.com`)"
      - "traefik.http.routers.backend-production.entrypoints=websecure"
      - "traefik.http.routers.backend-production.tls.certresolver=le"
      - "traefik.http.services.backend-production.loadbalancer.server.port=8000"
    volumes:
      - /srv/alien-commons/pro/media:/code/media
      - /srv/alien-commons/pro/static:/code/staticfiles

  backend-task-scheduler:
    build:
      context: ../../apps/backend
      dockerfile: Dockerfile
    working_dir: /code
    restart: unless-stopped
    command: >
      sh -c "python manage.py runscheduler"
    environment:
      DJANGO_ENV: pro
  
  backend-task-worker:
    build:
      context: ../../apps/backend
      dockerfile: Dockerfile
    working_dir: /code
    restart: unless-stopped
    command: >
      sh -c "python manage.py rqworker default email maintenance"
    environment:
      DJANGO_ENV: pro

  alloy:
    image: grafana/alloy:latest
    restart: unless-stopped
    command:
      - run
      - /etc/alloy/alloy.config.pro
    volumes:
      - ../../o11y/alloy/alloy.config.pro:/etc/alloy/alloy.config.pro:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - loki
  
  loki:
    image: grafana/loki:latest
    restart: unless-stopped
    command:
      - -config.file=/etc/loki/loki.pro.yml
    volumes:
      - ../../o11y/loki/loki.pro.yml:/etc/loki/loki.pro.yml:ro
      - /srv/alien-commons/pro/loki:/var/lib/loki/data

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ../../o11y/grafana/provisioning/datasources/loki-data.pro.yml:/etc/grafana/provisioning/datasources/loki-data.pro.yml:ro
      - ../../o11y/grafana/data:/var/lib/grafana/data
    depends_on:
      - loki

  frontend:
    build: 
      context: ../../apps/frontend
      dockerfile: Dockerfile
      args:
        VITE_MODE: production
    working_dir: /code
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend-production.rule=Host(`aliencommons.com`)"
      - "traefik.http.routers.frontend-production.entrypoints=websecure"
      - "traefik.http.routers.frontend-production.tls.certresolver=le"
      - "traefik.http.services.frontend-production.loadbalancer.server.port=80"

  media:
    image: nginx:alpine
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.media.rule=Host(`api.aliencommons.com`) && PathPrefix(`/media`)"
      - "traefik.http.routers.media.entrypoints=websecure"
      - "traefik.http.routers.media.tls.certresolver=le"
      - "traefik.http.services.media.loadbalancer.server.port=80"
    restart: unless-stopped
    volumes:
      - /srv/alien-commons/pro/media:/usr/share/nginx/html/media:ro
  
  static:
    image: nginx:alpine
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.static.rule=Host(`api.aliencommons.com`) && PathPrefix(`/static`)"
      - "traefik.http.routers.static.entrypoints=websecure"
      - "traefik.http.routers.static.tls.certresolver=le"
      - "traefik.http.services.static.loadbalancer.server.port=80"
    restart: unless-stopped
    volumes:
      - /srv/alien-commons/pro/static:/usr/share/nginx/html/static:ro

volumes:
  postgres_data_pro:
