x-stack-env: &stack-env
  env_file:
    - ../../env/.env.dev

name: alien-commons-dev

services:
  postgres:
    <<: *stack-env
    volumes:
      - postgres_data_dev:/var/lib/postgresql
    ports:
      - "5432:5432"

  redis:
    <<: *stack-env
    command: >
      sh -c 'redis-server --appendonly yes --requirepass "$$REDIS_PASSWORD"'
    ports:
      - "6379:6379"
  
  backend-init:
    <<: *stack-env
    build:
      context: ../../apps/backend
      dockerfile: Dockerfile
    working_dir: /code
    command: >
      sh -c "python manage.py migrate && python manage.py init_tasks"
    depends_on:
      - postgres
      - redis
    volumes:
      - ../../apps/backend:/code

  backend-api:
    <<: *stack-env
    build:
      context: ../../apps/backend
      dockerfile: Dockerfile
    working_dir: /code
    restart: unless-stopped
    command: >
      sh -c "gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ../../apps/backend:/code
    ports:
      - "8000:8000"

  backend-task-scheduler:
    <<: *stack-env
    build:
      context: ../../apps/backend
      dockerfile: Dockerfile
    working_dir: /code
    restart: unless-stopped
    command: >
      sh -c "python manage.py runscheduler"
    depends_on:
      - redis
      - postgres
    volumes:
      - ../../apps/backend:/code
  
  backend-task-worker:
    <<: *stack-env
    build:
      context: ../../apps/backend
      dockerfile: Dockerfile
    working_dir: /code
    restart: unless-stopped
    command: >
      sh -c "python manage.py rqworker default email maintenance"
    depends_on:
      - redis
      - postgres
    volumes:
      - ../../apps/backend:/code

  frontend:
    image: node:24
    restart: unless-stopped
    working_dir: /code
    command: >
      sh -c "
        pnpm install &&
        pnpm run dev
      "
    ports:
      - "8080:5173"
    volumes:
      - ../../apps/frontend:/code
      - /code/node_modules
  
  alloy:
    image: grafana/alloy:latest
    restart: unless-stopped
    command:
      - run
      - /etc/alloy/alloy.config.dev
    volumes:
      - ../../o11y/alloy/alloy.config.dev:/etc/alloy/alloy.config.dev:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - loki

  loki:
    image: grafana/loki:latest
    restart: unless-stopped
    command:
      - -config.file=/etc/loki/loki.dev.yml
    volumes:
      - ../../o11y/loki/loki.dev.yml:/etc/loki/loki.dev.yml:ro
      - ../../o11y/loki/data:/var/lib/loki/data
    ports:
      - "3100:3100"
  
  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ../../o11y/grafana/provisioning/datasources/loki-data.dev.yml:/etc/grafana/provisioning/datasources/loki-data.dev.yml:ro
      - ../../o11y/grafana/data:/var/lib/grafana/data
    depends_on:
      - loki
    ports:
      - "3000:3000"

volumes:
  postgres_data_dev:
