# Generated by Django 5.2.9 on 2026-02-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrontendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('debug', 'DEBUG'), ('info', 'INFO'), ('warn', 'WARN'), ('error', 'ERROR')], db_index=True, editable=False, max_length=10, verbose_name='level')),
                ('message', models.TextField(editable=False, verbose_name='message')),
                ('extra', models.JSONField(blank=True, editable=False, null=True, verbose_name='extra')),
                ('timestamp', models.DateTimeField(editable=False, verbose_name='timestamp')),
                ('page', models.CharField(editable=False, max_length=255, verbose_name='page')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'frontend log',
                'verbose_name_plural': 'frontend logs',
            },
        ),
    ]
