# Generated by Django 5.2.9 on 2026-02-28 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='articleevent',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_events_actors', to=settings.AUTH_USER_MODEL, verbose_name='actor'),
        ),
        migrations.AddField(
            model_name='articleevent',
            name='article_snapshot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_events', to='articles.articlesnapshot', verbose_name='snapshot'),
        ),
        migrations.AddField(
            model_name='sourcearticle',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_articles', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AddField(
            model_name='publishedarticle',
            name='source_article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='published_version', to='articles.sourcearticle', verbose_name='source article'),
        ),
        migrations.AddField(
            model_name='articlesnapshot',
            name='source_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_snapshots', to='articles.sourcearticle', verbose_name='source article'),
        ),
        migrations.AddField(
            model_name='articleevent',
            name='source_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_events', to='articles.sourcearticle', verbose_name='source articles'),
        ),
        migrations.AddIndex(
            model_name='sourcearticle',
            index=models.Index(fields=['author', 'created_at'], name='articles_so_author__7d3dd5_idx'),
        ),
        migrations.AddIndex(
            model_name='sourcearticle',
            index=models.Index(fields=['status', 'created_at'], name='articles_so_status_044214_idx'),
        ),
        migrations.AddIndex(
            model_name='articlesnapshot',
            index=models.Index(fields=['source_article', 'created_at'], name='articles_ar_source__073c0f_idx'),
        ),
        migrations.AddIndex(
            model_name='articlesnapshot',
            index=models.Index(fields=['moderation_status', 'created_at'], name='articles_ar_moderat_f773c4_idx'),
        ),
        migrations.AddIndex(
            model_name='articlesnapshot',
            index=models.Index(fields=['source_article', 'content_hash'], name='articles_ar_source__a682c0_idx'),
        ),
        migrations.AddIndex(
            model_name='articleevent',
            index=models.Index(fields=['source_article', 'created_at'], name='articles_ar_source__fe04d1_idx'),
        ),
        migrations.AddIndex(
            model_name='articleevent',
            index=models.Index(fields=['actor', 'created_at'], name='articles_ar_actor_i_7fd01f_idx'),
        ),
        migrations.AddIndex(
            model_name='articleevent',
            index=models.Index(fields=['article_snapshot', 'created_at'], name='articles_ar_article_9394d1_idx'),
        ),
        migrations.AddIndex(
            model_name='articleevent',
            index=models.Index(fields=['event_type', 'created_at'], name='articles_ar_event_t_b530f1_idx'),
        ),
    ]
