# Generated by Django 6.0.3 on 2026-03-21 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleevent',
            name='actor',
            field=models.ForeignKey(help_text='The actor of the article event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_events_actors', to=settings.AUTH_USER_MODEL, verbose_name='actor'),
        ),
        migrations.AlterField(
            model_name='articleevent',
            name='annotation',
            field=models.TextField(blank=True, help_text='The annotation of the article event', null=True, verbose_name='annotation'),
        ),
        migrations.AlterField(
            model_name='articleevent',
            name='article_snapshot',
            field=models.ForeignKey(help_text='The article snapshot of the article event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_events', to='articles.articlesnapshot', verbose_name='snapshot'),
        ),
        migrations.AlterField(
            model_name='articleevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The created DateTime of the article event', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='articleevent',
            name='event_type',
            field=models.IntegerField(choices=[(1, 'Submit'), (2, 'Withdraw'), (3, 'Approve'), (4, 'Reject'), (5, 'Unpublish'), (6, 'Delete')], help_text='The event type of the article event', verbose_name='event type'),
        ),
        migrations.AlterField(
            model_name='articleevent',
            name='source_article',
            field=models.ForeignKey(help_text='The source article of the article event', on_delete=django.db.models.deletion.CASCADE, related_name='article_events', to='articles.sourcearticle', verbose_name='source articles'),
        ),
        migrations.AlterField(
            model_name='articlesnapshot',
            name='content',
            field=models.JSONField(blank=True, default=dict, help_text='The content of the article snapshot', verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='articlesnapshot',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, default='', help_text='The content hash of the article snapshot', max_length=64, verbose_name='content hash'),
        ),
        migrations.AlterField(
            model_name='articlesnapshot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The created DateTime of the article snapshot', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='articlesnapshot',
            name='moderation_status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Withdrawn'), (3, 'Approved'), (4, 'Rejected')], db_index=True, default=1, help_text='The moderation status of the article snapshot', verbose_name='moderation status'),
        ),
        migrations.AlterField(
            model_name='articlesnapshot',
            name='source_article',
            field=models.ForeignKey(help_text='The source article of the article snapshot', on_delete=django.db.models.deletion.CASCADE, related_name='article_snapshots', to='articles.sourcearticle', verbose_name='source article'),
        ),
        migrations.AlterField(
            model_name='articlesnapshot',
            name='title',
            field=models.CharField(db_index=True, default='', help_text='The title of the article snapshot', max_length=60, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='publishedarticle',
            name='content',
            field=models.JSONField(blank=True, default=dict, help_text='The content of the published article', verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='publishedarticle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='publishedarticle',
            name='source_article',
            field=models.OneToOneField(help_text='The source article of the published version', on_delete=django.db.models.deletion.CASCADE, related_name='published_version', to='articles.sourcearticle', verbose_name='source article'),
        ),
        migrations.AlterField(
            model_name='publishedarticle',
            name='title',
            field=models.CharField(db_index=True, default='', help_text='The title of the published article', max_length=60, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='sourcearticle',
            name='author',
            field=models.ForeignKey(help_text='The author of the article', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_articles', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='sourcearticle',
            name='content',
            field=models.JSONField(blank=True, default=dict, help_text='The content of the article', verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='sourcearticle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='sourcearticle',
            name='last_moderation_at',
            field=models.DateTimeField(blank=True, help_text='The last moderation DateTime of the article', null=True, verbose_name='last moderation at'),
        ),
        migrations.AlterField(
            model_name='sourcearticle',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Pending'), (2, 'Published'), (3, 'Unpublished')], db_index=True, default=0, help_text='The status of the article', verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='sourcearticle',
            name='title',
            field=models.CharField(db_index=True, default='', help_text='The title of the article', max_length=60, verbose_name='title'),
        ),
    ]
