# Generated by Django 6.0.5 on 2026-05-10 01:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The created DateTime of the object', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='The updated DateTime of the object', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The UUID of the object', primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.IntegerField(choices=[(1, 'Off Topic'), (2, 'Spam or Promotion'), (3, 'Harassment or Abuse'), (4, 'Hate or Discrimination'), (5, 'Sexual Content'), (6, 'Violence or Threats'), (7, 'Politics or Ideology'), (8, 'Religious Controversy'), (9, 'Illegal Activity'), (99, 'Other')], help_text='The reason for the report', verbose_name='reason')),
                ('description', models.TextField(blank=True, default='', help_text="The reporter's optional description", verbose_name='description')),
                ('snapshot', models.JSONField(blank=True, default=dict, help_text='The target state when the report was submitted', verbose_name='snapshot')),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Reviewing'), (3, 'Resolved'), (4, 'Rejected')], db_index=True, default=1, help_text='The review status of the report', verbose_name='status')),
                ('resolution_note', models.TextField(blank=True, default='', help_text='Moderator note for the report resolution', verbose_name='resolution note')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='The DateTime when the report was resolved or rejected', null=True, verbose_name='resolved at')),
                ('target_type', models.IntegerField(help_text='The content target type at submission time', verbose_name='target type')),
                ('target_object_id', models.UUIDField(help_text="The reported object's ID at submission time", verbose_name='target object ID')),
                ('reporter', models.ForeignKey(help_text='The user who submitted the report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_reports', to=settings.AUTH_USER_MODEL, verbose_name='reporter')),
                ('resolved_by', models.ForeignKey(blank=True, help_text='The moderator who last resolved or rejected the report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_%(class)s_reports', to=settings.AUTH_USER_MODEL, verbose_name='resolved by')),
                ('target', models.ForeignKey(blank=True, help_text='The content target being reported', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_reports', to='core.contenttarget', verbose_name='target')),
            ],
            options={
                'verbose_name': 'content report',
                'verbose_name_plural': 'content reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reporter', 'created_at'], name='reports_con_reporte_94e22d_idx'), models.Index(fields=['status', 'created_at'], name='reports_con_status_bcd34e_idx'), models.Index(fields=['target_type', 'target_object_id'], name='reports_con_target__9a2c65_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The created DateTime of the object', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='The updated DateTime of the object', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The UUID of the object', primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.IntegerField(choices=[(1, 'Off Topic'), (2, 'Spam or Promotion'), (3, 'Harassment or Abuse'), (4, 'Hate or Discrimination'), (5, 'Sexual Content'), (6, 'Violence or Threats'), (7, 'Politics or Ideology'), (8, 'Religious Controversy'), (9, 'Illegal Activity'), (99, 'Other')], help_text='The reason for the report', verbose_name='reason')),
                ('description', models.TextField(blank=True, default='', help_text="The reporter's optional description", verbose_name='description')),
                ('snapshot', models.JSONField(blank=True, default=dict, help_text='The target state when the report was submitted', verbose_name='snapshot')),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Reviewing'), (3, 'Resolved'), (4, 'Rejected')], db_index=True, default=1, help_text='The review status of the report', verbose_name='status')),
                ('resolution_note', models.TextField(blank=True, default='', help_text='Moderator note for the report resolution', verbose_name='resolution note')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='The DateTime when the report was resolved or rejected', null=True, verbose_name='resolved at')),
                ('reported_user_id_snapshot', models.UUIDField(help_text="The reported user's ID at submission time", verbose_name='reported user ID snapshot')),
                ('reported_user', models.ForeignKey(blank=True, help_text='The user being reported', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_received', to=settings.AUTH_USER_MODEL, verbose_name='reported user')),
                ('reporter', models.ForeignKey(help_text='The user who submitted the report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_reports', to=settings.AUTH_USER_MODEL, verbose_name='reporter')),
                ('resolved_by', models.ForeignKey(blank=True, help_text='The moderator who last resolved or rejected the report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_%(class)s_reports', to=settings.AUTH_USER_MODEL, verbose_name='resolved by')),
            ],
            options={
                'verbose_name': 'user report',
                'verbose_name_plural': 'user reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reporter', 'created_at'], name='reports_use_reporte_b70008_idx'), models.Index(fields=['reported_user', 'created_at'], name='reports_use_reporte_398652_idx'), models.Index(fields=['status', 'created_at'], name='reports_use_status_9c690b_idx')],
            },
        ),
    ]
