# Generated by Django 5.2.9 on 2026-02-28 07:11

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation', models.TextField(blank=True, null=True, verbose_name='annotation')),
                ('event_type', models.IntegerField(choices=[(1, 'Submit'), (2, 'Withdraw'), (3, 'Approve'), (4, 'Reject'), (5, 'Unpublish'), (6, 'Delete')], verbose_name='event type')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'article event',
                'verbose_name_plural': 'article events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, default='', max_length=60, verbose_name='title')),
                ('content', models.JSONField(blank=True, default=dict, verbose_name='content')),
                ('content_hash', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='content hash')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('moderation_status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Withdrawn'), (3, 'Approved'), (4, 'Rejected')], db_index=True, default=1, verbose_name='moderation status')),
            ],
            options={
                'verbose_name': 'article snapshot',
                'verbose_name_plural': 'article snapshots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublishedArticle',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, default='', max_length=60, verbose_name='title')),
                ('content', models.JSONField(blank=True, default=dict, verbose_name='content')),
            ],
            options={
                'verbose_name': 'published article',
                'verbose_name_plural': 'published articles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SourceArticle',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('title', models.CharField(db_index=True, default='', max_length=60, verbose_name='title')),
                ('content', models.JSONField(blank=True, default=dict, verbose_name='content')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Pending'), (2, 'Published'), (3, 'Rejected'), (4, 'Unpublished'), (5, 'Deleted')], db_index=True, default=0, verbose_name='status')),
                ('last_moderation_at', models.DateTimeField(blank=True, null=True, verbose_name='last moderation at')),
            ],
            options={
                'verbose_name': 'source article',
                'verbose_name_plural': 'source articles',
                'ordering': ['-created_at'],
            },
        ),
    ]
