# Generated by Django 6.0.4 on 2026-05-02 01:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The created DateTime of the object', verbose_name='created at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The UUID of the object', primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.IntegerField(choices=[(1, 'Submit'), (2, 'Withdraw'), (3, 'Approve'), (4, 'Reject'), (5, 'Unpublish'), (6, 'Delete')], help_text='The event type of the article event', verbose_name='event type')),
            ],
            options={
                'verbose_name': 'article event',
                'verbose_name_plural': 'article events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The created DateTime of the object', verbose_name='created at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The UUID of the object', primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='The title of the article snapshot', max_length=100, verbose_name='title')),
                ('markdown', models.TextField(help_text='The article in Markdown format', verbose_name='article in markdown')),
                ('hash', models.CharField(db_index=True, default='', help_text='The hash value of the article snapshot', max_length=64, verbose_name='hash')),
                ('source_version', models.PositiveIntegerField(help_text='The source version of the article snapshot', verbose_name='source version')),
                ('moderation_status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Withdrawn'), (3, 'Approved'), (4, 'Rejected')], db_index=True, default=1, help_text='The moderation status of the article snapshot', verbose_name='moderation status')),
            ],
            options={
                'verbose_name': 'article snapshot',
                'verbose_name_plural': 'article snapshots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublishedArticle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The created DateTime of the object', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='The updated DateTime of the object', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The UUID of the object', primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='The title of the published article', max_length=100, verbose_name='title')),
                ('html', models.TextField(help_text='The article in HTML format', verbose_name='article in html')),
                ('publication_at', models.DateTimeField(db_index=True, help_text='Th DateTime of publication of the published article', verbose_name='published at')),
            ],
            options={
                'verbose_name': 'published article',
                'verbose_name_plural': 'published articles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SourceArticle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The created DateTime of the object', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='The updated DateTime of the object', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The UUID of the object', primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether the object is deleted', verbose_name='deleted')),
                ('title', models.CharField(blank=True, db_index=True, default='Untitled', help_text='The title of the article', max_length=100, verbose_name='title')),
                ('markdown', models.TextField(blank=True, default='', help_text='The article in Markdown format', verbose_name='article in markdown')),
                ('version', models.PositiveIntegerField(default=1, help_text='The current draft version of the source article', verbose_name='version')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Pending'), (2, 'Published'), (3, 'Unpublished')], db_index=True, default=0, help_text='The status of the article', verbose_name='status')),
                ('last_saved_at', models.DateTimeField(blank=True, help_text='The last saved DateTime of the article', null=True, verbose_name='last saved at')),
                ('last_moderation_at', models.DateTimeField(blank=True, help_text='The last moderation DateTime of the source article', null=True, verbose_name='last moderation at')),
            ],
            options={
                'verbose_name': 'source article',
                'verbose_name_plural': 'source articles',
                'ordering': ['-created_at'],
            },
        ),
    ]
