# Generated by Django 6.0.3 on 2026-04-05 01:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation', models.TextField(blank=True, help_text='The annotation of the article event', null=True, verbose_name='annotation')),
                ('event_type', models.IntegerField(choices=[(1, 'Submit'), (2, 'Withdraw'), (3, 'Approve'), (4, 'Reject'), (5, 'Unpublish'), (6, 'Delete')], help_text='The event type of the article event', verbose_name='event type')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The created DateTime of the article event', verbose_name='created at')),
            ],
            options={
                'verbose_name': 'article event',
                'verbose_name_plural': 'article events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, default='', help_text='The title of the article snapshot', max_length=60, verbose_name='title')),
                ('content', models.JSONField(blank=True, default=dict, help_text='The content of the article snapshot', verbose_name='content')),
                ('content_hash', models.CharField(blank=True, db_index=True, default='', help_text='The content hash of the article snapshot', max_length=64, verbose_name='content hash')),
                ('moderation_status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Withdrawn'), (3, 'Approved'), (4, 'Rejected')], db_index=True, default=1, help_text='The moderation status of the article snapshot', verbose_name='moderation status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The created DateTime of the article snapshot', verbose_name='created at')),
            ],
            options={
                'verbose_name': 'article snapshot',
                'verbose_name_plural': 'article snapshots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublishedArticle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, default='', help_text='The title of the published article', max_length=60, verbose_name='title')),
                ('content', models.JSONField(blank=True, default=dict, help_text='The content of the published article', verbose_name='content')),
            ],
            options={
                'verbose_name': 'published article',
                'verbose_name_plural': 'published articles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SourceArticle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('title', models.CharField(db_index=True, default='', help_text='The title of the article', max_length=60, verbose_name='title')),
                ('content', models.JSONField(blank=True, default=dict, help_text='The content of the article', verbose_name='content')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Pending'), (2, 'Published'), (3, 'Unpublished')], db_index=True, default=0, help_text='The status of the article', verbose_name='status')),
                ('last_moderation_at', models.DateTimeField(blank=True, help_text='The last moderation DateTime of the article', null=True, verbose_name='last moderation at')),
            ],
            options={
                'verbose_name': 'source article',
                'verbose_name_plural': 'source articles',
                'ordering': ['-created_at'],
            },
        ),
    ]
