# Generated by Django 6.0.3 on 2026-04-05 12:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleevent',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='The UUID of the object', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='articlesnapshot',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='The UUID of the object', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='publishedarticle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The created DateTime of the object', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='publishedarticle',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='The UUID of the object', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='publishedarticle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The updated DateTime of the object', verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='sourcearticle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The created DateTime of the object', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='sourcearticle',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='The UUID of the object', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sourcearticle',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether the object is deleted', verbose_name='deleted'),
        ),
        migrations.AlterField(
            model_name='sourcearticle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The updated DateTime of the object', verbose_name='updated at'),
        ),
    ]
