# Generated by Codex on 2026-05-07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, editable=False, help_text="The created DateTime of the object", verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True, help_text="The updated DateTime of the object", verbose_name="updated at")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, help_text="The UUID of the object", primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(db_index=True, help_text="The title of the collection", max_length=100, verbose_name="title")),
                ("description", models.TextField(blank=True, default="", help_text="The description of the collection", verbose_name="description")),
                ("author", models.ForeignKey(help_text="The author of the collection", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="article_collections", to=settings.AUTH_USER_MODEL, verbose_name="author")),
            ],
            options={
                "verbose_name": "collection",
                "verbose_name_plural": "collections",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CollectionItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, editable=False, help_text="The created DateTime of the object", verbose_name="created at")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, help_text="The UUID of the object", primary_key=True, serialize=False, verbose_name="ID")),
                ("position", models.PositiveIntegerField(help_text="The item's position in the collection", verbose_name="position")),
                ("collection", models.ForeignKey(help_text="The collection that contains this item", on_delete=django.db.models.deletion.CASCADE, related_name="items", to="articles.collection", verbose_name="collection")),
                ("published_article", models.ForeignKey(help_text="The published article in the collection", on_delete=django.db.models.deletion.CASCADE, related_name="collection_items", to="articles.publishedarticle", verbose_name="published article")),
            ],
            options={
                "verbose_name": "collection item",
                "verbose_name_plural": "collection items",
                "ordering": ["collection", "position", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="collection",
            index=models.Index(fields=["author", "created_at"], name="articles_co_author__8d9622_idx"),
        ),
        migrations.AddIndex(
            model_name="collectionitem",
            index=models.Index(fields=["collection", "position"], name="articles_co_collect_d90500_idx"),
        ),
        migrations.AddIndex(
            model_name="collectionitem",
            index=models.Index(fields=["published_article", "created_at"], name="articles_co_publish_5a05ed_idx"),
        ),
        migrations.AddConstraint(
            model_name="collectionitem",
            constraint=models.UniqueConstraint(fields=("collection", "published_article"), name="unique_collection_published_article"),
        ),
        migrations.AddConstraint(
            model_name="collectionitem",
            constraint=models.UniqueConstraint(fields=("collection", "position"), name="unique_collection_item_position"),
        ),
    ]
