# Generated by Django 6.0.3 on 2026-03-23 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_articleevent_actor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleevent',
            name='actor',
            field=models.ForeignKey(help_text='The actor of the article event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_events', to=settings.AUTH_USER_MODEL, verbose_name='actor'),
        ),
        migrations.AlterField(
            model_name='articleevent',
            name='article_snapshot',
            field=models.ForeignKey(help_text='The article snapshot of the article event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_events', to='articles.articlesnapshot', verbose_name='snapshot'),
        ),
    ]
