# Generated by Codex on 2026-05-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_collection_collectionitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sourcearticle",
            name="markdown",
            field=models.TextField(
                blank=True,
                default="# Untitled",
                help_text="The article in Markdown format",
                verbose_name="article in markdown",
            ),
        ),
    ]
