# Generated by Django 6.0.5 on 2026-05-09 05:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0004_alter_sourcearticle_markdown'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTarget',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The created DateTime of the object', verbose_name='created at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The UUID of the object', primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.IntegerField(choices=[(1, 'Published Article'), (2, 'Comment')], db_index=True, help_text='The type of object this content target points to', verbose_name='target type')),
                ('comment', models.OneToOneField(blank=True, help_text='The comment this content target points to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_target', to='comments.comment', verbose_name='comment')),
                ('published_article', models.OneToOneField(blank=True, help_text='The published article this content target points to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_target', to='articles.publishedarticle', verbose_name='published article')),
            ],
            options={
                'verbose_name': 'content target',
                'verbose_name_plural': 'content targets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_type', 'created_at'], name='core_conten_target__1122bd_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('comment__isnull', True), ('published_article__isnull', False), ('target_type', 1)), models.Q(('comment__isnull', False), ('published_article__isnull', True), ('target_type', 2)), _connector='OR'), name='content_target_requires_exactly_one_object')],
            },
        ),
    ]
