# Generated by Django 6.0.6 on 2026-06-21 06:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        ('comments', '0001_initial'),
        ('posts', '0002_communitypost_mentions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTarget',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The created DateTime of the object', verbose_name='created at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The UUID of the object', primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.IntegerField(choices=[(1, 'Article Publication'), (2, 'Comment'), (3, 'Community Post')], db_index=True, help_text='The type of object this content target points to', verbose_name='target type')),
                ('article_publication', models.OneToOneField(blank=True, help_text='The article publication this content target points to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_target', to='articles.articlepublication', verbose_name='article publication')),
                ('comment', models.OneToOneField(blank=True, help_text='The comment this content target points to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_target', to='comments.comment', verbose_name='comment')),
                ('community_post', models.OneToOneField(blank=True, help_text='The community post this content target points to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_target', to='posts.communitypost', verbose_name='community post')),
            ],
            options={
                'verbose_name': 'content target',
                'verbose_name_plural': 'content targets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_type', 'created_at'], name='core_conten_target__1122bd_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('article_publication__isnull', False), ('comment__isnull', True), ('community_post__isnull', True), ('target_type', 1)), models.Q(('article_publication__isnull', True), ('comment__isnull', False), ('community_post__isnull', True), ('target_type', 2)), models.Q(('article_publication__isnull', True), ('comment__isnull', True), ('community_post__isnull', False), ('target_type', 3)), _connector='OR'), name='content_target_requires_exactly_one_object')],
            },
        ),
    ]
