# Generated by Django 6.0.5 on 2026-05-21 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_sourcearticle_markdown'),
        ('comments', '0003_comment_mentions'),
        ('core', '0001_initial'),
        ('posts', '0002_communitypost_mentions'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contenttarget',
            name='content_target_requires_exactly_one_object',
        ),
        migrations.AddField(
            model_name='contenttarget',
            name='community_post',
            field=models.OneToOneField(blank=True, help_text='The community post this content target points to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_target', to='posts.communitypost', verbose_name='community post'),
        ),
        migrations.AlterField(
            model_name='contenttarget',
            name='target_type',
            field=models.IntegerField(choices=[(1, 'Published Article'), (2, 'Comment'), (3, 'Community Post')], db_index=True, help_text='The type of object this content target points to', verbose_name='target type'),
        ),
        migrations.AddConstraint(
            model_name='contenttarget',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('comment__isnull', True), ('community_post__isnull', True), ('published_article__isnull', False), ('target_type', 1)), models.Q(('comment__isnull', False), ('community_post__isnull', True), ('published_article__isnull', True), ('target_type', 2)), models.Q(('comment__isnull', True), ('community_post__isnull', False), ('published_article__isnull', True), ('target_type', 3)), _connector='OR'), name='content_target_requires_exactly_one_object'),
        ),
    ]
