# Generated by Django 6.0.6 on 2026-06-21 06:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The created DateTime of the object', verbose_name='created at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The UUID of the object', primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.IntegerField(choices=[(1, 'Like'), (2, 'Dislike')], help_text="The user's reaction type", verbose_name='reaction type')),
                ('target', models.ForeignKey(help_text='The target being reacted to', on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='core.contenttarget', verbose_name='target')),
                ('user', models.ForeignKey(help_text='The user who made the reaction', on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'reaction',
                'verbose_name_plural': 'reactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='reactions_r_user_id_09910f_idx'), models.Index(fields=['target', 'reaction_type'], name='reactions_r_target__006b9b_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'target'), name='unique_reaction_per_user_target')],
            },
        ),
    ]
