# Generated by Django 6.0.5 on 2026-05-08 12:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0004_alter_sourcearticle_markdown'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactionTarget',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The created DateTime of the object', verbose_name='created at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The UUID of the object', primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.IntegerField(choices=[(1, 'Published Article')], db_index=True, default=1, help_text='The type of object this reaction target points to', verbose_name='target type')),
                ('published_article', models.OneToOneField(blank=True, help_text='The published article this reaction target points to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reaction_target', to='articles.publishedarticle', verbose_name='published article')),
            ],
            options={
                'verbose_name': 'reaction target',
                'verbose_name_plural': 'reaction targets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The created DateTime of the object', verbose_name='created at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The UUID of the object', primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.IntegerField(choices=[(1, 'Like'), (2, 'Dislike')], help_text="The user's reaction type", verbose_name='reaction type')),
                ('user', models.ForeignKey(help_text='The user who made the reaction', on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('target', models.ForeignKey(help_text='The target being reacted to', on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='reactions.reactiontarget', verbose_name='target')),
            ],
            options={
                'verbose_name': 'reaction',
                'verbose_name_plural': 'reactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='reactiontarget',
            index=models.Index(fields=['target_type', 'created_at'], name='reactions_r_target__716285_idx'),
        ),
        migrations.AddConstraint(
            model_name='reactiontarget',
            constraint=models.CheckConstraint(condition=models.Q(('published_article__isnull', False), ('target_type', 1)), name='reaction_target_requires_matching_object'),
        ),
        migrations.AddIndex(
            model_name='reaction',
            index=models.Index(fields=['user', 'created_at'], name='reactions_r_user_id_09910f_idx'),
        ),
        migrations.AddIndex(
            model_name='reaction',
            index=models.Index(fields=['target', 'reaction_type'], name='reactions_r_target__006b9b_idx'),
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.UniqueConstraint(fields=('user', 'target'), name='unique_reaction_per_user_target'),
        ),
    ]
