# Generated by Django 6.0.5 on 2026-05-09 05:21

import django.db.models.deletion
from django.db import migrations, models


def copy_reaction_targets_to_content_targets(apps, schema_editor):
    ReactionTarget = apps.get_model('reactions', 'ReactionTarget')
    ContentTarget = apps.get_model('core', 'ContentTarget')

    content_targets = [
        ContentTarget(
            id=reaction_target.id,
            created_at=reaction_target.created_at,
            target_type=1,
            published_article_id=reaction_target.published_article_id,
        )
        for reaction_target in ReactionTarget.objects.all()
    ]
    ContentTarget.objects.bulk_create(content_targets, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('reactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reactiontarget',
            name='reactions_r_target__716285_idx',
        ),
        migrations.RemoveConstraint(
            model_name='reactiontarget',
            name='reaction_target_requires_matching_object',
        ),
        migrations.RunPython(
            copy_reaction_targets_to_content_targets,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='reaction',
            name='target',
            field=models.ForeignKey(help_text='The target being reacted to', on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='core.contenttarget', verbose_name='target'),
        ),
        migrations.DeleteModel(
            name='ReactionTarget',
        ),
    ]
