# Generated by Django 6.0.3 on 2026-04-05 12:34

import django.db.models.deletion
import django.utils.timezone
import users.models.users
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The UUID of the object', primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='The username of the user', max_length=30, unique=True, verbose_name='username')),
                ('avatar', models.ImageField(blank=True, help_text='The avatar of the user', null=True, storage=users.models.users.AvatarStorage(), upload_to=users.models.users.avatar_upload_to, verbose_name='avatar')),
                ('signature', models.CharField(blank=True, default='This player is somewhat mysterious...', help_text='The signature of the user', max_length=60, verbose_name='signature')),
                ('is_moderator', models.BooleanField(default=False, help_text='Whether the user is a moderator', verbose_name='moderator status')),
                ('is_email_verified', models.BooleanField(default=False, editable=False, help_text='Whether at least an email of the user is verified', verbose_name='email verified')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', users.models.users.ProfileManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The created DateTime of the object', verbose_name='created at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The UUID of the object', primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(help_text="The session's session key", max_length=40, unique=True, verbose_name='session key')),
                ('user_agent', models.TextField(blank=True, help_text="The session's user agent", null=True, verbose_name='user agent')),
                ('browser', models.CharField(blank=True, help_text="The session's browser", max_length=100, null=True, verbose_name='browser')),
                ('os', models.CharField(blank=True, help_text="The session's operating system", max_length=100, null=True, verbose_name='operating system')),
                ('device', models.CharField(blank=True, help_text="The session's device", max_length=100, null=True, verbose_name='device')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text="The session's IP address", null=True, verbose_name='IP address')),
                ('last_accessed_at', models.DateField(help_text="The session's last accessed Date", verbose_name='last accessed at')),
                ('user', models.ForeignKey(help_text='The user of the session', on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user session',
                'verbose_name_plural': 'user sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The created DateTime of the object', verbose_name='created at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The UUID of the object', primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='The email of the email address', max_length=254, unique=True, verbose_name='email')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the email is verified', verbose_name='verified')),
                ('is_primary', models.BooleanField(default=False, help_text='Whether the email is the primary email of the user', verbose_name='primary')),
                ('user', models.ForeignKey(help_text='The user of the email address', on_delete=django.db.models.deletion.CASCADE, related_name='related_emails', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'email',
                'verbose_name_plural': 'emails',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('user',), name='unique_user_primary_emails')],
            },
        ),
    ]
