# Generated by Django 6.0.5 on 2026-05-08 10:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The created DateTime of the object', verbose_name='created at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The UUID of the object', primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_to', models.ForeignKey(help_text='The user being subscribed to', on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to=settings.AUTH_USER_MODEL, verbose_name='subscribed to')),
                ('subscriber', models.ForeignKey(help_text='The user who subscribes', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='subscriber')),
            ],
            options={
                'verbose_name': 'user subscription',
                'verbose_name_plural': 'user subscriptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subscriber', 'created_at'], name='users_users_subscri_232125_idx'), models.Index(fields=['subscribed_to', 'created_at'], name='users_users_subscri_112a86_idx')],
                'constraints': [models.UniqueConstraint(fields=('subscriber', 'subscribed_to'), name='unique_user_subscription'), models.CheckConstraint(condition=models.Q(('subscriber', models.F('subscribed_to')), _negated=True), name='prevent_self_subscription')],
            },
        ),
    ]
