# Generated by Codex on 2026-03-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailaddress",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                default=None,
                editable=False,
                null=True,
                verbose_name="created at",
            ),
            preserve_default=False,
        ),
    ]
