# Generated by Django 6.0.3 on 2026-03-21 06:43

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailaddress_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaddress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='The created DateTime of the email address', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='email',
            field=models.EmailField(help_text='The email of the email address', max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Whether the email is the primary email of the user', verbose_name='primary'),
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether the email is verified', verbose_name='verified'),
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='user',
            field=models.ForeignKey(help_text='The user of the email address', on_delete=django.db.models.deletion.CASCADE, related_name='related_emails', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='The avatar of the user', null=True, storage=users.models.AvatarStorage(), upload_to=users.models.avatar_upload_to, verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, editable=False, help_text='Whether at least an email of the user is verified', verbose_name='email verified'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_moderator',
            field=models.BooleanField(default=False, help_text='Whether the user is a moderator', verbose_name='moderator status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='signature',
            field=models.CharField(blank=True, default='This player is somewhat mysterious...', help_text='The signature of the user', max_length=60, verbose_name='signature'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='The username of the user', max_length=30, unique=True, verbose_name='username'),
        ),
    ]
